function [row_index_final_H,col_index_final_H] = Jump2DLagrangianHessianInitialSP(iter,NUM_X)
%JUMP2DLAGRANGIANHESSIANINITIALSP
%    [ROW_INDEX_FINAL_H,COL_INDEX_FINAL_H] = JUMP2DLAGRANGIANHESSIANINITIALSP(ITER,NUM_X)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Aug-2019 12:38:35

t2 = NUM_X.*iter;
t3 = t2+1.0;
t4 = t2+2.0;
t5 = t2+3.0;
t6 = t2+4.0;
t7 = t2+5.0;
t8 = t2+6.0;
t9 = t2+7.0;
t10 = t2+8.0;
t11 = t2+9.0;
t12 = [t2;t3;t4;t5;t6;t7;t8;t9;t10;t11];
row_index_final_H = t12;
if nargout > 1
    col_index_final_H = t12;
end
