function [row_index_final_CJ,col_index_final_CJ] = Jump2DConstraintJacobianFinalSP(iter,NUM_X,NUM_C)
%JUMP2DCONSTRAINTJACOBIANFINALSP
%    [ROW_INDEX_FINAL_CJ,COL_INDEX_FINAL_CJ] = JUMP2DCONSTRAINTJACOBIANFINALSP(ITER,NUM_X,NUM_C)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Aug-2019 12:38:33

t2 = NUM_C.*iter;
t3 = t2+2.0;
t4 = t2+3.0;
t5 = t2+5.0;
t6 = t2+1.0;
t7 = t2+4.0;
row_index_final_CJ = [t2;t6;t3;t4;t7;t5;t2;t3;t4;t5;t6;t3;t7;t5;t2+6.0;t2+7.0;t2;t3;t4;t5;t6;t3;t7;t5;t2+8.0;t2+9.0];
if nargout > 1
    t8 = NUM_X.*iter;
    t9 = t8+6.0;
    t10 = t8+7.0;
    t11 = t8+8.0;
    t12 = t8+9.0;
    col_index_final_CJ = [t8;t8+1.0;t8+2.0;t8+3.0;t8+4.0;t8+5.0;t9;t9;t9;t9;t10;t10;t10;t10;t10;t10;t11;t11;t11;t11;t12;t12;t12;t12;t12;t12];
end
