function constraints_initial = Jump2DConstraintsInitial(in1,in2,in3,in4,dt,in6,m,Iyy,g,mu_g)
%JUMP2DCONSTRAINTSINITIAL
%    CONSTRAINTS_INITIAL = JUMP2DCONSTRAINTSINITIAL(IN1,IN2,IN3,IN4,DT,IN6,M,IYY,G,MU_G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Aug-2019 12:38:32

Fxb = in2(3,:);
Fxf = in2(1,:);
Fzb = in2(4,:);
Fzf = in2(2,:);
dphi = in1(6,:);
dphi0 = in3(6,:);
dx = in1(4,:);
dx0 = in3(4,:);
dz = in1(5,:);
dz0 = in3(5,:);
phi = in1(3,:);
phi0 = in3(3,:);
rxb = in6(3,:);
rxf = in6(1,:);
rzb = in6(4,:);
rzf = in6(2,:);
sb = in4(2,:);
sf = in4(1,:);
x = in1(1,:);
x0 = in3(1,:);
z = in1(2,:);
z0 = in3(2,:);
t2 = dt.^2;
t3 = 1.0./m;
t4 = Fxb.*sb;
t5 = Fxf.*sf;
t6 = t4+t5;
t7 = Fzb.*sb;
t8 = Fzf.*sf;
t9 = t7+t8;
t10 = 1.0./Iyy;
t11 = Fxb.*rzb;
t12 = t11-Fzb.*rxb;
t13 = sb.*t12;
t14 = Fxf.*rzf;
t15 = t14-Fzf.*rxf;
t16 = sf.*t15;
t17 = t13+t16;
t18 = mu_g-1.0;
t19 = mu_g+1.0;
constraints_initial = [x-x0-dt.*dx0-t2.*t3.*t6.*(1.0./2.0);z-z0-dt.*dz0-g.*t2.*(1.0./2.0)-t2.*t3.*t9.*(1.0./2.0);phi-phi0-dphi0.*dt-t2.*t10.*t17.*(1.0./2.0);dx-dx0-dt.*t3.*t6;dz-dz0-dt.*g-dt.*t3.*t9;dphi-dphi0-dt.*t10.*t17;-Fzf.*sf.*t18;-Fzf.*sf.*t19;-Fzb.*sb.*t18;-Fzb.*sb.*t19];
