function lagrangian_hessian_nz = Jump2DLagrangianHessian(in1,in2,obj_factor)
%JUMP2DLAGRANGIANHESSIAN
%    LAGRANGIAN_HESSIAN_NZ = JUMP2DLAGRANGIANHESSIAN(IN1,IN2,OBJ_FACTOR)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Aug-2019 12:38:34

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
r1 = in2(1,:);
r2 = in2(2,:);
r3 = in2(3,:);
r4 = in2(4,:);
lagrangian_hessian_nz = [obj_factor.*q1.*2.0;obj_factor.*q2.*2.0;obj_factor.*q3.*2.0;obj_factor.*q4.*2.0;obj_factor.*q5.*2.0;obj_factor.*q6.*2.0;obj_factor.*r1.*2.0;obj_factor.*r2.*2.0;obj_factor.*r3.*2.0;obj_factor.*r4.*2.0];
