function [decision_vars0,inputs_ref0] = Jump2DInitialize(in1,in2,in3,dt,in5,m,Iyy,g)
%JUMP2DINITIALIZE
%    [DECISION_VARS0,INPUTS_REF0] = JUMP2DINITIALIZE(IN1,IN2,IN3,DT,IN5,M,IYY,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Aug-2019 12:38:29

Fxb = in2(3,:);
Fxf = in2(1,:);
Fzb = in2(4,:);
Fzf = in2(2,:);
dphi0 = in1(6,:);
dx0 = in1(4,:);
dz0 = in1(5,:);
phi0 = in1(3,:);
rxb = in5(3,:);
rxf = in5(1,:);
rzb = in5(4,:);
rzf = in5(2,:);
sb = in3(2,:);
sf = in3(1,:);
x0 = in1(1,:);
z0 = in1(2,:);
t2 = dt.^2;
t3 = 1.0./m;
t4 = Fxb.*sb;
t5 = Fxf.*sf;
t6 = t4+t5;
t7 = Fzb.*sb;
t8 = Fzf.*sf;
t9 = t7+t8;
t10 = 1.0./Iyy;
t11 = Fxb.*rzb;
t12 = t11-Fzb.*rxb;
t13 = sb.*t12;
t14 = Fxf.*rzf;
t15 = t14-Fzf.*rxf;
t16 = sf.*t15;
t17 = t13+t16;
decision_vars0 = [x0+dt.*dx0+t2.*t3.*t6.*(1.0./2.0);z0+dt.*dz0+g.*t2.*(1.0./2.0)+t2.*t3.*t9.*(1.0./2.0);phi0+dphi0.*dt+t2.*t10.*t17.*(1.0./2.0);dx0+dt.*t3.*t6;dz0+dt.*g+dt.*t3.*t9;dphi0+dt.*t10.*t17;0.0;0.0;0.0;0.0];
if nargout > 1
    inputs_ref0 = [0.0;0.0;0.0;0.0];
end
