function robot = get_robot_params(r)

% Get robot parameters (link lengths, gear ratios, rotor inertia)
% actual link mass parameters are in the spatial_v2 model struct
% r = 0 is cheetah 3, otherwise mini-cheetah

if(r == 0)
    robot = struct(...
        'l1',.342,...
        'l2',.345,...
        'I_rot',1e-3,...  % TODO check with ben on this
        'gr_abad_hip',7.66666,...
        'gr_knee',8.846,...
        'body_width',.256,...
        'body_height',.2,...
        'body_length',.6,...
        'body_mass',36,...
        'leg_rad',.03,...
        'l1_mass',2*.5,...
        'l2_mass',2*.5,...
        'i_body_mult',1,...
        'rotor_mass',5e-1,...
        'rotor_inertia',[5e-4 0 0;
                         0 1e-3 0;
                         0  0  5e-4]);
else
    robot = struct(...
        'l1',.209,...
        'l2',.175,...
        'I_rot',63e-6,...  % TODO check with ben on this
        'gr_abad_hip',6,...
        'gr_knee',9.33,...
        'body_width',.1,...
        'body_height',.1,...
        'body_length',.27,...
<<<<<<< Updated upstream
        'body_mass',7,...
        'leg_rad',.02,...
        'l1_mass',.1,...
        'l2_mass',.1,...
=======
<<<<<<< HEAD
        'body_mass',8.5,...
        'leg_rad',.02,...
        'l1_mass',.2,...
        'l2_mass',.2,...
=======
        'body_mass',7,...
        'leg_rad',.02,...
        'l1_mass',.1,...
        'l2_mass',.1,...
>>>>>>> origin/master
>>>>>>> Stashed changes
        'i_body_mult',7);  
end

end

