function [decision_vars0,inputs_ref0] = Jump2DInitialize(in1,in2,in3,dt,in5,m,Iyy,g)
%JUMP2DINITIALIZE
%    [DECISION_VARS0,INPUTS_REF0] = JUMP2DINITIALIZE(IN1,IN2,IN3,DT,IN5,M,IYY,G)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Aug-2019 12:28:03

Fxb = in2(3,:);
Fxf = in2(1,:);
Fzb = in2(4,:);
Fzf = in2(2,:);
dphi0 = in1(6,:);
dx0 = in1(4,:);
dz0 = in1(5,:);
phi0 = in1(3,:);
rxb = in5(3,:);
rxf = in5(1,:);
rzb = in5(4,:);
rzf = in5(2,:);
sb = in3(2,:);
sf = in3(1,:);
x0 = in1(1,:);
z0 = in1(2,:);
t2 = Fxb.*rzb;
t3 = Fzb.*rxb;
t4 = Fxf.*rzf;
t5 = Fzf.*rxf;
t6 = Fxb.*sb;
t7 = Fzb.*sb;
t8 = Fxf.*sf;
t9 = Fzf.*sf;
t10 = dt.^2;
t11 = 1.0./Iyy;
t12 = 1.0./m;
t13 = -t3;
t14 = -t5;
t15 = t6+t8;
t16 = t7+t9;
t17 = t2+t13;
t18 = t4+t14;
t19 = sb.*t17;
t20 = sf.*t18;
t21 = t19+t20;
decision_vars0 = [x0+dt.*dx0+(t10.*t12.*t15)./2.0;z0+dt.*dz0+(g.*t10)./2.0+(t10.*t12.*t16)./2.0;phi0+dphi0.*dt+(t10.*t11.*t21)./2.0;dx0+dt.*t12.*t15;dz0+dt.*g+dt.*t12.*t16;dphi0+dt.*t11.*t21;0.0;0.0;0.0;0.0];
if nargout > 1
    inputs_ref0 = [0.0;0.0;0.0;0.0];
end
