function [row_index_CJ,col_index_CJ] = Jump2DConstraintJacobianSP(iter,NUM_X,NUM_C)
%JUMP2DCONSTRAINTJACOBIANSP
%    [ROW_INDEX_CJ,COL_INDEX_CJ] = JUMP2DCONSTRAINTJACOBIANSP(ITER,NUM_X,NUM_C)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Aug-2019 12:28:05

t2 = NUM_C.*iter;
t3 = NUM_X.*iter;
t4 = t2+1.0;
t9 = t3+3.0;
t5 = t4+1.0;
t10 = t9+1.0;
t6 = t5+1.0;
t11 = t10+1.0;
t7 = t6+1.0;
t12 = t11+1.1e+1;
t8 = t7+1.0;
row_index_CJ = [t2;t4;t5;t2;t6;t4;t7;t5;t8;t2;t4;t5;t6;t7;t8;t2;t5;t6;t8;t4;t5;t7;t8;t8+1.0;t8+2.0;t2;t5;t6;t8;t4;t5;t7;t8;t8+3.0;t8+4.0];
if nargout > 1
    t13 = t12+1.0;
    t14 = t13+1.0;
    t15 = t14+1.0;
    col_index_CJ = [t3;t3+1.0;t3+2.0;t9;t9;t10;t10;t11;t11;t11+5.0;t11+6.0;t11+7.0;t11+8.0;t11+9.0;t11+1.0e+1;t12;t12;t12;t12;t13;t13;t13;t13;t13;t13;t14;t14;t14;t14;t15;t15;t15;t15;t15;t15];
end
