function constraint_jacobian_initial_nz = Jump2DConstraintJacobianInitial(in1,dt,in3,m,Iyy,mu_g)
%JUMP2DCONSTRAINTJACOBIANINITIAL
%    CONSTRAINT_JACOBIAN_INITIAL_NZ = JUMP2DCONSTRAINTJACOBIANINITIAL(IN1,DT,IN3,M,IYY,MU_G)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Aug-2019 12:28:05

rxb = in3(3,:);
rxf = in3(1,:);
rzb = in3(4,:);
rzf = in3(2,:);
sb = in1(2,:);
sf = in1(1,:);
t2 = dt.^2;
t3 = mu_g+1.0;
t4 = 1.0./Iyy;
t5 = 1.0./m;
t6 = mu_g-1.0;
t7 = dt.*sb.*t5;
t8 = dt.*sf.*t5;
t11 = (sb.*t2.*t5)./2.0;
t12 = (sf.*t2.*t5)./2.0;
t9 = -t7;
t10 = -t8;
t13 = -t11;
t14 = -t12;
constraint_jacobian_initial_nz = [1.0;1.0;1.0;1.0;1.0;1.0;t14;rzf.*sf.*t2.*t4.*(-1.0./2.0);t10;-dt.*rzf.*sf.*t4;t14;(rxf.*sf.*t2.*t4)./2.0;t10;dt.*rxf.*sf.*t4;-sf.*t6;-sf.*t3;t13;rzb.*sb.*t2.*t4.*(-1.0./2.0);t9;-dt.*rzb.*sb.*t4;t13;(rxb.*sb.*t2.*t4)./2.0;t9;dt.*rxb.*sb.*t4;-sb.*t6;-sb.*t3];
