function [row_index_final_H,col_index_final_H] = Jump2DLagrangianHessianInitialSP(iter,NUM_X)
%JUMP2DLAGRANGIANHESSIANINITIALSP
%    [ROW_INDEX_FINAL_H,COL_INDEX_FINAL_H] = JUMP2DLAGRANGIANHESSIANINITIALSP(ITER,NUM_X)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Aug-2019 12:28:06

t2 = NUM_X.*iter;
t3 = t2+1.0;
t4 = t3+1.0;
t5 = t4+1.0;
t6 = t5+1.0;
t7 = t6+1.0;
t8 = t7+1.0;
t9 = t8+1.0;
t10 = t9+1.0;
t11 = t10+1.0;
row_index_final_H = [t2;t3;t4;t5;t6;t7;t8;t9;t10;t11];
if nargout > 1
    col_index_final_H = [t2;t3;t4;t5;t6;t7;t8;t9;t10;t11];
end
