function constraints_final = Jump2DConstraintsFinal(in1,in2,in3,in4,dt,in6,m,Iyy,g,mu_g)
%JUMP2DCONSTRAINTSFINAL
%    CONSTRAINTS_FINAL = JUMP2DCONSTRAINTSFINAL(IN1,IN2,IN3,IN4,DT,IN6,M,IYY,G,MU_G)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Aug-2019 12:28:04

Fxb = in2(3,:);
Fxf = in2(1,:);
Fzb = in2(4,:);
Fzf = in2(2,:);
dphi = in1(6,:);
dphi0 = in3(6,:);
dx = in1(4,:);
dx0 = in3(4,:);
dz = in1(5,:);
dz0 = in3(5,:);
phi = in1(3,:);
phi0 = in3(3,:);
rxb = in6(3,:);
rxf = in6(1,:);
rzb = in6(4,:);
rzf = in6(2,:);
sb = in4(2,:);
sf = in4(1,:);
x = in1(1,:);
x0 = in3(1,:);
z = in1(2,:);
z0 = in3(2,:);
t2 = Fxb.*rzb;
t3 = Fzb.*rxb;
t4 = Fxf.*rzf;
t5 = Fzf.*rxf;
t6 = Fxb.*sb;
t7 = Fzb.*sb;
t8 = Fxf.*sf;
t9 = Fzf.*sf;
t10 = dt.^2;
t11 = mu_g+1.0;
t12 = 1.0./Iyy;
t13 = 1.0./m;
t14 = mu_g-1.0;
t15 = -t3;
t16 = -t5;
t17 = t6+t8;
t18 = t7+t9;
t19 = t2+t15;
t20 = t4+t16;
t21 = sb.*t19;
t22 = sf.*t20;
t23 = t21+t22;
constraints_final = [x-x0-dt.*dx0-(t10.*t13.*t17)./2.0;z-z0-dt.*dz0-(g.*t10)./2.0-(t10.*t13.*t18)./2.0;phi-phi0-dphi0.*dt-(t10.*t12.*t23)./2.0;dx-dx0-dt.*t13.*t17;dz-dz0-dt.*g-dt.*t13.*t18;dphi-dphi0-dt.*t12.*t23;-t9.*t14;-t9.*t11;-t7.*t14;-t7.*t11];
